Documentation update for options missing in targetGlobalSettings()
AdobeDocs/target-developers pull request #209
Opened 2023-01-28 00:51 UTC by ericfichtel

## Description

The solution to the customer issue logged in the ticket below is to configure the `pollingInterval` setting in `targetGlobalSettings()`, however that was missing from the documentation. This PR adds that setting, along with `propertyToken` and `artifactLocation` to the documentation. 

## Related Issue

https://jira.corp.adobe.com/browse/TNT-46359

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-02-02 16:38 UTC, ericfichtel commented
Closing to add reviews to a new pull request

2023-02-07 19:20 UTC, dcottingham requested changes

2023-02-07 19:20 UTC, dcottingham commented on src/pages/implement/client-side/atjs/atjs-functions/targetglobalsettings.md
> +### propertyToken
I don't think we'll need to add propertyToken to targetGlobalSettings after all.  I looked into [the code](https://git.corp.adobe.com/TnT/atjs-library-v2/blob/2d92da412c01ddffceabb5236feab12956d04370/src/delivery/params/index.js#L83) and it looks like if user wants to set a property in at.js they would use the `targetPageParams.at_property`

2023-02-07 19:20 UTC, dcottingham commented on src/pages/implement/client-side/atjs/atjs-functions/targetglobalsettings.md
> +* **Description**: Interval that at.js fetches a new version of an artifact and updates the cache
Let's also specify for users that 300000 is also the minimum value - you can verify that [here](https://github.com/adobe/target-nodejs-sdk/blob/2635d7dfb06554f5bd282ae399140d3c21723388/packages/target-decisioning-engine/src/constants.js#L8).

2023-02-08 20:58 UTC, jasonwaters commented on src/pages/implement/client-side/atjs/atjs-functions/targetglobalsettings.md
> +* **Type**: String
![sting-wink-gif](https://user-images.githubusercontent.com/427213/217649399-626aadf8-b06f-4f2d-bfb9-b84bf90927df.gif)

2023-02-08 21:58 UTC, ericfichtel commented on src/pages/implement/client-side/atjs/atjs-functions/targetglobalsettings.md
> +* **Type**: String
I don't drink coffee I take tea

2023-02-08 22:26 UTC, dcottingham approved these changes
Changes look good to me

2023-02-09 02:04 UTC, ericfichtel commented
Hi @judy-kim looks like we are good from our side - would you be able to review this when you have the chance? Thanks!

2023-02-09 02:11 UTC, judy-kim approved these changes

2023-02-09 02:13 UTC, merged